events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://nextjs:3000;
        }

        location /api {
            proxy_pass http://express-api:4000;
        }
    }
}
